"""Tests for .seg.nrrd key/value parsing into SegmentationExtension."""

from __future__ import annotations

from pathlib import Path

import nrrd
import pytest

from duckn.models import SEG_EXTENSION_VERSION, SegmentationExtension
from duckn.seg_nrrd import parse_seg_keyvalues, serialize_seg_extension

DATA_DIR = Path(__file__).parent / "data" / "real-world"

SEG_NRRD_FILES = sorted(DATA_DIR.glob("*.seg.nrrd"))


def _slicer(obj) -> dict:
    """The metadata.slicer dict of a segment or extension."""
    return (obj.metadata or {}).get("slicer", {})


# ---------------------------------------------------------------------------
# Unit tests for parse_seg_keyvalues
# ---------------------------------------------------------------------------


def test_no_segmentation_keys():
    """Non-segmentation keyvalues should return None and pass through."""
    kv = {"foo": "bar", "baz": "42"}
    ext, remaining = parse_seg_keyvalues(kv)
    assert ext is None
    assert remaining == kv


def test_minimal_segment():
    """A single segment with only ID and LabelValue should parse."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, remaining = parse_seg_keyvalues(kv)
    assert ext is not None
    assert remaining == {}
    assert len(ext.segments) == 1
    assert ext.segments[0].id == "S1"
    assert ext.segments[0].label_value == 1
    assert ext.version == SEG_EXTENSION_VERSION


def test_global_fields():
    """Global Segmentation_* fields should parse correctly."""
    kv = {
        "Segmentation_MasterRepresentation": "Binary labelmap",
        "Segmentation_ContainedRepresentationNames": "Binary labelmap|Closed surface|",
        "Segmentation_ReferenceImageExtentOffset": "0 0 0",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, remaining = parse_seg_keyvalues(kv)
    assert ext is not None
    assert ext.source_representation == "binary-labelmap"
    assert _slicer(ext)["contained_representations"] == ["binary-labelmap", "closed-surface"]
    assert _slicer(ext)["reference_extent_offset"] == [0, 0, 0]


def test_source_representation_preferred_over_master():
    """SourceRepresentation should take precedence over MasterRepresentation."""
    kv = {
        "Segmentation_MasterRepresentation": "Binary labelmap",
        "Segmentation_SourceRepresentation": "Fractional labelmap",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext is not None
    assert ext.source_representation == "fractional-labelmap"


def test_conversion_parameters():
    """ConversionParameters should parse name|value|description."""
    kv = {
        "Segmentation_ConversionParameters": (
            "Smoothing factor|0.5|Range: 0.0 to 1.0.&"
            "Joint smoothing|0|Perform joint smoothing.&"
        ),
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext is not None
    params = _slicer(ext)["conversion_parameters"]
    assert "Smoothing factor" in params
    assert params["Smoothing factor"]["value"] == "0.5"
    assert params["Smoothing factor"]["description"] == "Range: 0.0 to 1.0."
    assert params["Joint smoothing"]["value"] == "0"


def test_conversion_parameters_escaped_newlines():
    """Backslash-n in descriptions should be unescaped."""
    kv = {
        "Segmentation_ConversionParameters": r"End capping|1|Line1.\nLine2.&",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    params = _slicer(ext)["conversion_parameters"]
    assert params["End capping"]["description"] == "Line1.\nLine2."


def test_segment_fields():
    """Per-segment scalar fields should parse correctly."""
    kv = {
        "Segment0_ID": "Seg1",
        "Segment0_Name": "Liver",
        "Segment0_NameAutoGenerated": "0",
        "Segment0_Color": "0.5 0.6 0.7",
        "Segment0_ColorAutoGenerated": "1",
        "Segment0_LabelValue": "3",
        "Segment0_Layer": "2",
        "Segment0_Extent": "10 20 30 40 50 60",
    }
    ext, _ = parse_seg_keyvalues(kv)
    seg = ext.segments[0]
    assert seg.id == "Seg1"
    assert seg.name == "Liver"
    assert _slicer(seg)["name_auto_generated"] is False
    assert seg.color == [0.5, 0.6, 0.7]
    assert _slicer(seg)["color_auto_generated"] is True
    assert seg.label_value == 3
    assert seg.layer == 2
    assert seg.extent == [10, 20, 30, 40, 50, 60]


def test_multi_label_value():
    """Space-separated label values should become a list."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "2 3",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext.segments[0].label_value == [2, 3]


def test_tags_and_terminology():
    """Tags including TerminologyEntry should parse into dicom/designations/tags."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": (
            "Segmentation.Status:inprogress|"
            "TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list"
            "~SCT^85756007^Tissue~SCT^85756007^Tissue~^^"
            "~Anatomic codes - DICOM master list~^^~^^|"
        ),
    }
    ext, _ = parse_seg_keyvalues(kv)
    seg = ext.segments[0]

    # Tags (non-terminology)
    assert _slicer(seg)["tags"] == {"Status": "inprogress"}

    # DICOM classification
    assert seg.dicom is not None
    assert seg.dicom.category.scheme == "SCT"
    assert seg.dicom.category.code == "85756007"
    assert seg.dicom.category.meaning == "Tissue"
    assert seg.dicom.type.code == "85756007"

    # Designation from type code
    assert seg.designations is not None
    assert len(seg.designations) == 1
    assert seg.designations[0].scheme == "SCT"
    assert seg.designations[0].code == "85756007"

    # Terminology registry
    assert ext.terminologies is not None
    assert "SCT" in ext.terminologies
    assert ext.terminologies["SCT"].name == "SNOMED Clinical Terms"


def test_empty_dicom_omitted():
    """If all DICOM code slots are empty, dicom should be None."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": "TerminologyEntry:ctx1~^^~^^~^^~ctx2~^^~^^|",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext.segments[0].dicom is None
    assert ext.segments[0].designations is None


def test_remaining_keys_preserved():
    """Non-segmentation keys should be returned in remaining dict."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "CustomKey": "custom_value",
        "Segmentation_MasterRepresentation": "Binary labelmap",
    }
    ext, remaining = parse_seg_keyvalues(kv)
    assert ext is not None
    assert remaining == {"CustomKey": "custom_value"}


def test_multiple_segments_ordered():
    """Segments should be ordered by index."""
    kv = {
        "Segment2_ID": "C",
        "Segment2_LabelValue": "3",
        "Segment0_ID": "A",
        "Segment0_LabelValue": "1",
        "Segment1_ID": "B",
        "Segment1_LabelValue": "2",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert [s.id for s in ext.segments] == ["A", "B", "C"]


def test_srt_terminology_known():
    """SRT scheme should map to 'DICOM SR Coding Scheme'."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": (
            "TerminologyEntry:ctx~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~ctx~^^~^^|"
        ),
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext.terminologies["SRT"].name == "DICOM SR Coding Scheme"


def test_model_validates():
    """Parsed extension should validate against SegmentationExtension model."""
    kv = {
        "Segmentation_MasterRepresentation": "Binary labelmap",
        "Segmentation_ContainedRepresentationNames": "Binary labelmap|",
        "Segmentation_ReferenceImageExtentOffset": "0 0 0",
        "Segment0_ID": "Seg1",
        "Segment0_Name": "Full",
        "Segment0_LabelValue": "1",
        "Segment0_Layer": "0",
        "Segment0_Color": "0.5 0.6 0.7",
        "Segment0_ColorAutoGenerated": "1",
        "Segment0_NameAutoGenerated": "0",
        "Segment0_Extent": "10 20 30 40 50 60",
        "Segment0_Tags": (
            "Segmentation.Status:inprogress|"
            "TerminologyEntry:ctx~SCT^85756007^Tissue~SCT^85756007^Tissue~^^~ctx~^^~^^|"
        ),
    }
    ext, _ = parse_seg_keyvalues(kv)
    # Round-trip through model_dump → SegmentationExtension
    dumped = ext.model_dump(exclude_none=True)
    reloaded = SegmentationExtension(**dumped)
    assert reloaded.segments[0].id == "Seg1"


# ---------------------------------------------------------------------------
# Integration tests against real-world .seg.nrrd files
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "seg_file",
    SEG_NRRD_FILES,
    ids=[f.name for f in SEG_NRRD_FILES],
)
def test_real_world_parses(seg_file: Path):
    """Each real-world .seg.nrrd file should parse without errors."""
    header = nrrd.read_header(str(seg_file))
    keyvalues: dict[str, str] = {}
    for k, v in header.items():
        if not k.startswith(("type", "dimension", "space", "sizes", "encoding", "endian",
                             "kinds", "data file", "datafile", "content",
                             "sample units", "spacings", "thicknesses",
                             "axis m", "axism", "centerings", "labels", "units",
                             "min", "max", "old", "number", "line", "byte")):
            keyvalues[k] = str(v)

    ext, remaining = parse_seg_keyvalues(keyvalues)
    assert ext is not None, f"No segmentation found in {seg_file.name}"
    assert len(ext.segments) > 0

    # Validate model round-trip
    dumped = ext.model_dump(exclude_none=True)
    reloaded = SegmentationExtension(**dumped)
    assert len(reloaded.segments) == len(ext.segments)


@pytest.mark.parametrize(
    "seg_file",
    SEG_NRRD_FILES,
    ids=[f.name for f in SEG_NRRD_FILES],
)
def test_real_world_no_seg_keys_in_remaining(seg_file: Path):
    """After parsing, no Segment* or Segmentation_* keys should remain."""
    header = nrrd.read_header(str(seg_file))
    keyvalues: dict[str, str] = {}
    for k, v in header.items():
        if not k.startswith(("type", "dimension", "space", "sizes", "encoding", "endian",
                             "kinds", "data file", "datafile", "content",
                             "sample units", "spacings", "thicknesses",
                             "axis m", "axism", "centerings", "labels", "units",
                             "min", "max", "old", "number", "line", "byte")):
            keyvalues[k] = str(v)

    _, remaining = parse_seg_keyvalues(keyvalues)
    for key in remaining:
        assert not key.startswith("Segment"), f"Seg key leaked to remaining: {key}"
        assert not key.startswith("Segmentation_"), f"Seg key leaked to remaining: {key}"


@pytest.mark.parametrize(
    "seg_file",
    SEG_NRRD_FILES,
    ids=[f.name for f in SEG_NRRD_FILES],
)
def test_real_world_segment_ids_unique(seg_file: Path):
    """Segment IDs within each file should be unique."""
    header = nrrd.read_header(str(seg_file))
    keyvalues: dict[str, str] = {}
    for k, v in header.items():
        if not k.startswith(("type", "dimension", "space", "sizes", "encoding", "endian",
                             "kinds", "data file", "datafile", "content",
                             "sample units", "spacings", "thicknesses",
                             "axis m", "axism", "centerings", "labels", "units",
                             "min", "max", "old", "number", "line", "byte")):
            keyvalues[k] = str(v)

    ext, _ = parse_seg_keyvalues(keyvalues)
    ids = [s.id for s in ext.segments]
    assert len(ids) == len(set(ids)), f"Duplicate segment IDs in {seg_file.name}: {ids}"


# ---------------------------------------------------------------------------
# Round-trip tests: parse → serialize → re-parse
# ---------------------------------------------------------------------------


def test_serialize_minimal():
    """Minimal extension should serialize and re-parse."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Name": "Liver",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    ext2, _ = parse_seg_keyvalues(flat)
    assert ext2.segments[0].id == "S1"
    assert ext2.segments[0].name == "Liver"
    assert ext2.segments[0].label_value == 1


def test_serialize_global_fields():
    """Global fields should round-trip through serialize."""
    kv = {
        "Segmentation_MasterRepresentation": "Binary labelmap",
        "Segmentation_ContainedRepresentationNames": "Binary labelmap|Closed surface|",
        "Segmentation_ReferenceImageExtentOffset": "0 0 0",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)

    assert flat["Segmentation_MasterRepresentation"] == "Binary labelmap"
    assert "Binary labelmap" in flat["Segmentation_ContainedRepresentationNames"]
    assert "Closed surface" in flat["Segmentation_ContainedRepresentationNames"]
    assert flat["Segmentation_ReferenceImageExtentOffset"] == "0 0 0"


def test_serialize_conversion_parameters():
    """ConversionParameters should round-trip, re-escaping newlines."""
    kv = {
        "Segmentation_ConversionParameters": r"End capping|1|Line1.\nLine2.&Factor|0.5|Desc.&",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    ext2, _ = parse_seg_keyvalues(flat)
    params = _slicer(ext2)["conversion_parameters"]
    assert params["End capping"]["description"] == "Line1.\nLine2."
    assert params["Factor"]["value"] == "0.5"


def test_serialize_segment_fields():
    """All per-segment fields should round-trip."""
    kv = {
        "Segment0_ID": "Seg1",
        "Segment0_Name": "Liver",
        "Segment0_NameAutoGenerated": "0",
        "Segment0_Color": "0.5 0.6 0.7",
        "Segment0_ColorAutoGenerated": "1",
        "Segment0_LabelValue": "3",
        "Segment0_Layer": "2",
        "Segment0_Extent": "10 20 30 40 50 60",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    ext2, _ = parse_seg_keyvalues(flat)
    seg = ext2.segments[0]
    assert seg.name == "Liver"
    assert _slicer(seg)["name_auto_generated"] is False
    assert seg.color == [0.5, 0.6, 0.7]
    assert _slicer(seg)["color_auto_generated"] is True
    assert seg.label_value == 3
    assert seg.layer == 2
    assert seg.extent == [10, 20, 30, 40, 50, 60]


def test_serialize_tags_and_dicom():
    """Tags + TerminologyEntry should round-trip through serialize."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": (
            "Segmentation.Status:inprogress|"
            "TerminologyEntry:ctx~SCT^85756007^Tissue~SCT^85756007^Tissue~^^~ctx~^^~^^|"
        ),
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    ext2, _ = parse_seg_keyvalues(flat)
    seg = ext2.segments[0]
    assert _slicer(seg)["tags"] == {"Status": "inprogress"}
    assert seg.dicom.category.code == "85756007"
    assert seg.designations[0].scheme == "SCT"


def test_serialize_multi_label():
    """Multi-value label_value should round-trip."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "2 3",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    ext2, _ = parse_seg_keyvalues(flat)
    assert ext2.segments[0].label_value == [2, 3]


@pytest.mark.parametrize(
    "seg_file",
    SEG_NRRD_FILES,
    ids=[f.name for f in SEG_NRRD_FILES],
)
def test_real_world_round_trip(seg_file: Path):
    """parse → serialize → re-parse should preserve segment structure."""
    header = nrrd.read_header(str(seg_file))
    keyvalues: dict[str, str] = {}
    for k, v in header.items():
        if not k.startswith(("type", "dimension", "space", "sizes", "encoding", "endian",
                             "kinds", "data file", "datafile", "content",
                             "sample units", "spacings", "thicknesses",
                             "axis m", "axism", "centerings", "labels", "units",
                             "min", "max", "old", "number", "line", "byte")):
            keyvalues[k] = str(v)

    ext1, _ = parse_seg_keyvalues(keyvalues)
    flat = serialize_seg_extension(ext1)
    ext2, remaining = parse_seg_keyvalues(flat)

    assert len(ext2.segments) == len(ext1.segments)
    assert [s.id for s in ext2.segments] == [s.id for s in ext1.segments]
    assert [s.name for s in ext2.segments] == [s.name for s in ext1.segments]
    assert [s.label_value for s in ext2.segments] == [s.label_value for s in ext1.segments]
    assert ext2.source_representation == ext1.source_representation
    assert not remaining  # no leaked keys


# ---------------------------------------------------------------------------
# Legacy fidelity tests: unmodified model replays original strings
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "seg_file",
    SEG_NRRD_FILES,
    ids=[f.name for f in SEG_NRRD_FILES],
)
def test_real_world_byte_exact_with_legacy(seg_file: Path):
    """Unmodified model should replay original strings byte-exactly."""
    header = nrrd.read_header(str(seg_file))
    keyvalues: dict[str, str] = {}
    for k, v in header.items():
        if not k.startswith(("type", "dimension", "space", "sizes", "encoding", "endian",
                             "kinds", "data file", "datafile", "content",
                             "sample units", "spacings", "thicknesses",
                             "axis m", "axism", "centerings", "labels", "units",
                             "min", "max", "old", "number", "line", "byte")):
            keyvalues[k] = str(v)

    ext, _ = parse_seg_keyvalues(keyvalues)
    flat = serialize_seg_extension(ext)

    # Every consumed seg key should come back byte-exact
    for key in keyvalues:
        if key.startswith("Segment") or key.startswith("Segmentation_"):
            assert flat.get(key) == keyvalues[key], (
                f"{key} mismatch:\n  orig: {keyvalues[key]!r}\n  got:  {flat.get(key)!r}"
            )


def test_source_representation_key_spelling_preserved():
    """A file using the modern Source spelling must not come back as Master."""
    kv = {
        "Segmentation_SourceRepresentation": "Binary labelmap",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    assert flat["Segmentation_SourceRepresentation"] == "Binary labelmap"
    assert "Segmentation_MasterRepresentation" not in flat


def test_unmodelled_seg_keys_survive_round_trip():
    """Keys the model doesn't represent are consumed on parse — don't lose them."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_MysteryField": "keep me",
        "Segmentation_UnknownThing": "keep me too",
    }
    ext, remaining = parse_seg_keyvalues(kv)
    assert remaining == {}  # consumed, so serialization is the only way back
    flat = serialize_seg_extension(ext)
    assert flat["Segment0_MysteryField"] == "keep me"
    assert flat["Segmentation_UnknownThing"] == "keep me too"


def test_designation_modifier_survives_without_dicom_type_modifier():
    """Laterality lives on the designation in §7.1-shaped data."""
    ext = SegmentationExtension(
        version=SEG_EXTENSION_VERSION,
        segments=[
            {
                "id": "S1",
                "name": "Right kidney",
                "label_value": 1,
                "designations": [
                    {
                        "scheme": "SCT",
                        "code": "64033007",
                        "meaning": "Kidney",
                        "modifier": {"scheme": "SCT", "code": "24028007", "meaning": "Right"},
                    }
                ],
                "dicom": {
                    "category": {"scheme": "SCT", "code": "123037004", "meaning": "Body structure"},
                    "type": {"scheme": "SCT", "code": "64033007", "meaning": "Kidney"},
                },
            }
        ],
    )
    flat = serialize_seg_extension(ext)
    assert "24028007" in flat["Segment0_Tags"]

    ext2, _ = parse_seg_keyvalues(flat)
    assert ext2.segments[0].designations[0].modifier.code == "24028007"


def test_two_part_coded_entry_keeps_the_code():
    """meaning is optional, so scheme^code must not be discarded."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": "TerminologyEntry:ctx~SCT^123037004~SCT^64033007~^^~ctx2~^^~^^|",
    }
    ext, _ = parse_seg_keyvalues(kv)
    seg = ext.segments[0]
    assert seg.dicom.category.code == "123037004"
    assert seg.dicom.category.meaning is None
    assert seg.designations[0].code == "64033007"


def test_missing_label_value_does_not_claim_background():
    """0 is background; a segment without LabelValue must not claim it."""
    kv = {
        "Segment0_ID": "S1",
        "Segment1_ID": "S2",
        "Segment1_LabelValue": "7",
    }
    with pytest.warns(UserWarning, match="LabelValue"):
        ext, _ = parse_seg_keyvalues(kv)
    assert ext.segments[0].label_value == 1
    assert ext.segments[1].label_value == 7


def test_non_labelmap_master_representation_is_readable():
    """A Closed surface .seg.nrrd should parse, not raise."""
    kv = {
        "Segmentation_MasterRepresentation": "Closed surface",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext.source_representation == "closed-surface"


def test_tag_key_prefix_is_symmetric():
    """A tag without the Segmentation. prefix must not gain one."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": "Segmentation.Status:done|Vendor.Reviewer:mh|",
    }
    ext, _ = parse_seg_keyvalues(kv)
    tags = _slicer(ext.segments[0])["tags"]
    assert tags == {"Status": "done", "Vendor.Reviewer": "mh"}

    ext.segments[0].name = "modified"  # force fresh generation, not legacy replay
    flat = serialize_seg_extension(ext)
    assert "Segmentation.Status:done" in flat["Segment0_Tags"]
    assert "Vendor.Reviewer:mh" in flat["Segment0_Tags"]
    assert "Segmentation.Vendor.Reviewer" not in flat["Segment0_Tags"]


def test_legacy_dropped_when_model_modified():
    """If the model is modified, legacy should be ignored and fresh strings generated."""
    kv = {
        "Segmentation_SourceRepresentation": "Binary labelmap",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": (
            "TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list"
            "~SCT^85756007^Tissue~SCT^85756007^Tissue~^^"
            "~Anatomic codes - DICOM master list~^^~^^|"
        ),
    }
    ext, _ = parse_seg_keyvalues(kv)

    # Modify the model
    ext.segments[0].name = "Modified"

    flat = serialize_seg_extension(ext)
    # Should use generated values, not legacy
    assert flat["Segment0_Name"] == "Modified"
    # Key falls back to MasterRepresentation (generated default)
    assert "Segmentation_MasterRepresentation" in flat

