"""The house spelling is American, in every tracked text file (2026-09-22).

Ported from haversack (commit 514332c), where it was made critical after new scripts picked up
"centre" from a sibling repository's API. The reason is DRIFT: every British word already in a
file is a template the next edit copies, so a clean tree has to be held clean by a test, not by
care. duckn's specs also sit beside DICOM, NIfTI and NRRD, which are American ("Window Center"),
so a British word in a spec reads as a second convention.

The detector is an explicit list of British forms, never a suffix rule: "-ise" would flag advise,
exercise, precise and noise, and "-our" would flag four and contour. Identifiers are split before
matching (``centre_err``, ``colourMap``, ``NormaliseHU``), so a local name drifts no more quietly
than a comment does. Python, Markdown, JavaScript and TypeScript are all scanned: ``js/`` and
``slicer/`` are where a sibling project's spelling arrives first.

What is never respelled: a name the spec defines or a file carries - a field, an extension, an
enum value, a DICOM keyword, an NRRD field, a Slicer ``Segment*`` key. Those are wire formats.
None of duckn's is British today; if one ever is, it goes in ``GLOBAL_OK`` with its reason.

Exceptions have to be named where they are and have to stay true:

- A line that must quote someone else's spelling (an external standard's text, a paper's title,
  a third-party attribute) says so on that line: ``spelling: allow <word>``. In Markdown, put it
  in an HTML comment so it does not render: ``<!-- spelling: allow colour -->``. It allows that
  word on that line only, and a pragma whose word is no longer on its line fails the test - an
  exception may not outlive its reason.
- This file lists the British forms it looks for, so it is not scanned; the detector tests below
  are what hold it to its job.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path, PurePosixPath

import pytest

ROOT = Path(__file__).resolve().parents[1]
SELF = Path(__file__).resolve().relative_to(ROOT).as_posix()
TEXT = {".py", ".md", ".toml", ".yml", ".yaml", ".json", ".html", ".txt", ".cfg", ".ini", ".sh",
        ".js", ".mjs", ".cjs", ".ts", ".tsx", ".cmake"}
NOT_SCANNED = {
    SELF: "lists the British forms it detects",
    "js/duckn-cornerstone/package-lock.json": "generated by npm; names third-party packages, and JSON "
                                              "has no comment to hold a pragma",
}

# -- the British forms, generated from stems -----------------------------------------------------
_OUR = ("colour behaviour favour honour neighbour labour humour flavour harbour rumour vapour odour "
        "tumour armour endeavour savour vigour rigour valour splendour parlour").split()
_OUR_SUFFIX = ("", "s", "ed", "ing", "ful", "less", "hood", "hoods", "al", "ally", "ite", "ites", "able",
               "ably", "map", "maps", "bar", "bars", "ation", "ise", "ised", "ize", "ized", "er", "ers")
_RE = ("centre metre litre fibre calibre theatre spectre sombre lustre meagre sabre ochre "
       "millimetre centimetre kilometre micrometre nanometre millilitre epicentre").split()
_RE_SUFFIX = ("", "s", "d", "line", "lines", "point", "points")
_ISE = ("normalis organis recognis optimis minimis maximis visualis summaris generalis initialis serialis "
        "deserialis parallelis prioritis categoris characteris finalis standardis synchronis customis authoris "
        "utilis emphasis realis specialis materialis tokenis quantis discretis binaris randomis regularis "
        "penalis vectoris rasteris digitis memoris apologis criticis localis centralis stabilis neutralis "
        "capitalis canonicalis mobilis polaris symbolis harmonis idealis sanitis anonymis pseudonymis "
        "reorganis reinitialis uninitialis unrecognis").split()
_ISE_SUFFIX = ("e", "es", "ed", "ing", "er", "ers", "ation", "ations", "able")
_YSE = {"analyse": "analyze", "analysed": "analyzed", "analysing": "analyzing", "analyser": "analyzer",
        "analysers": "analyzers", "paralyse": "paralyze", "paralysed": "paralyzed", "catalyse": "catalyze",
        "catalysed": "catalyzed", "catalysing": "catalyzing"}          # never "analyses": a US plural too
_LL = ("labelled labelling unlabelled relabelled relabelling modelled modelling unmodelled modeller "
       "modellers travelled travelling traveller travellers signalled signalling levelled levelling "
       "fuelled fuelling channelled channelling tunnelled funnelled totalled totalling dialled dialling "
       "counselled marshalled marshalling cancelled cancelling jewellery woollen").split()
_OTHER = {
    "licence": "license", "licences": "licenses", "grey": "gray", "greys": "grays", "greyscale": "grayscale",
    "whilst": "while", "amongst": "among", "artefact": "artifact", "artefacts": "artifacts",
    "programme": "program", "programmes": "programs", "catalogue": "catalog", "catalogues": "catalogs",
    "catalogued": "cataloged", "analogue": "analog", "defence": "defense", "offence": "offense",
    "pretence": "pretense", "judgement": "judgment", "judgements": "judgments", "aluminium": "aluminum",
    "sceptical": "skeptical", "manoeuvre": "maneuver", "manoeuvres": "maneuvers", "learnt": "learned",
    "spelt": "spelled", "fulfil": "fulfill", "fulfilment": "fulfillment", "enrol": "enroll",
    "enrolment": "enrollment", "instalment": "installment", "skilful": "skillful", "wilful": "willful",
    "centring": "centering",
    # the medical forms this domain meets
    "oedema": "edema", "oesophagus": "esophagus", "oesophageal": "esophageal", "haemorrhage": "hemorrhage",
    "haemorrhagic": "hemorrhagic", "haematoma": "hematoma", "haemoglobin": "hemoglobin",
    "haematocrit": "hematocrit", "anaemia": "anemia", "ischaemia": "ischemia", "ischaemic": "ischemic",
    "leukaemia": "leukemia", "paediatric": "pediatric", "paediatrics": "pediatrics", "anaesthesia": "anesthesia",
    "anaesthetic": "anesthetic", "foetal": "fetal", "foetus": "fetus", "diarrhoea": "diarrhea",
    "oestrogen": "estrogen", "orthopaedic": "orthopedic", "caesarean": "cesarean", "gynaecology": "gynecology",
    "coeliac": "celiac",
}


def _forms() -> dict[str, str]:
    out = {}
    for s in _OUR:
        for x in _OUR_SUFFIX:
            out[s + x] = s.replace("our", "or") + x.replace("ise", "ize")
    for s in _RE:
        for x in _RE_SUFFIX:
            out[s + x] = s[:-2] + "er" + ("ed" if x == "d" else x)
    for s in _ISE:
        for x in _ISE_SUFFIX:
            out[s + x] = s[:-1] + "z" + x
    out.pop("emphasis", None)                                  # the noun is the same in both
    for w in _LL:
        i = w.rindex("ll")
        out[w] = w[:i] + w[i + 1:]
    out.update(_YSE)
    out.update(_OTHER)
    return out


BRITISH = _forms()

# British words that are a wire format duckn defines or carries, with the reason. None today.
GLOBAL_OK: dict[str, str] = {}

_WORD = re.compile(r"[A-Za-z]+")
_PART = re.compile(r"[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z]+|[A-Z]+")
_PRAGMA = re.compile(r"spelling:\s*allow\s+([A-Za-z ,]+)")


def tokens(line: str):
    """Every word of a line, identifiers split at underscores, digits and camelCase, lower-cased."""
    for w in _WORD.findall(line):
        yield w.lower()
        parts = _PART.findall(w)
        if len(parts) > 1:
            for p in parts:
                yield p.lower()


def british_in(line: str) -> list[tuple[str, str]]:
    seen, out = set(), []
    for t in tokens(line):
        if t in BRITISH and t not in GLOBAL_OK and t not in seen:
            seen.add(t)
            out.append((t, BRITISH[t]))
    return out


def tracked_text_files(root: Path = ROOT) -> list[str]:
    r = subprocess.run(["git", "ls-files", "-z"], cwd=root, capture_output=True)
    if r.returncode:
        raise AssertionError("the spelling test reads the tracked files from git: run it in a git checkout "
                             f"({r.stderr.decode(errors='replace').strip()})")
    names = [n for n in r.stdout.decode().split("\0") if n]
    return sorted(n for n in names if PurePosixPath(n).suffix in TEXT and n not in NOT_SCANNED)


def scan(names, root: Path = ROOT) -> tuple[list[str], list[str]]:
    """``(violations, stale pragmas)`` as ``path:line: ...`` lines."""
    bad, stale = [], []
    for n in names:
        try:
            text = (root / n).read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError):
            continue
        for i, line in enumerate(text.splitlines(), 1):
            m = _PRAGMA.search(line)
            allowed = {w.lower() for w in re.split(r"[ ,]+", m.group(1)) if w} if m else set()
            body = line[:m.start()] + line[m.end():] if m else line      # the pragma names its word: not evidence
            found = british_in(body)
            for w in sorted(allowed - {t for t, _ in found}):
                stale.append(f"{n}:{i}: 'spelling: allow {w}' but {w!r} is not on this line - remove the pragma")
            for t, us in found:
                if t not in allowed:
                    bad.append(f"{n}:{i}: {t!r} -> {us!r}")
    return bad, stale


# -- the repo --------------------------------------------------------------------------------------


def test_no_british_spelling_in_tracked_text():
    bad, _ = scan(tracked_text_files())
    msg = ("house spelling is American (drift: every British word is a template the next edit copies). "
           "Quoting someone else's text? put 'spelling: allow <word>' on that line "
           "(in Markdown, inside <!-- -->). Never respell a field name or key the spec defines.\n")
    assert bad == [], msg + "\n".join(bad)


def test_every_pragma_still_has_its_reason():
    _, stale = scan(tracked_text_files())
    assert stale == [], "\n".join(stale)


def test_the_scan_covers_the_package_the_specs_js_and_slicer():
    """A file filter that matched nothing would pass the tests above trivially."""
    names = set(tracked_text_files())
    assert len(names) > 100
    for must in ("src/duckn/models.py", "README.md", "CHANGELOG.md", "pyproject.toml",
                 "docs/duckn-spec.md", "docs/segmentation-ext-spec.md", "tests/test_docs.py",
                 "js/duckn-reader/src/index.js", "js/duckn-spatial/src/index.js",
                 "js/duckn-cornerstone/src/index.ts", "js/duckn-cornerstone/scripts/sync-spatial.mjs",
                 "slicer/SlicerDuckn/SlicerDucknIO/SlicerDucknIO.py"):
        assert must in names, must
    assert SELF not in names


def test_without_git_the_scan_fails_rather_than_passing_empty(tmp_path):
    with pytest.raises(AssertionError, match="git checkout"):
        tracked_text_files(tmp_path)


# -- the detector ----------------------------------------------------------------------------------


@pytest.mark.parametrize("line, word", [
    ("the centre of the box", "centre"), ("colourMap = cm.viridis", "colour"),
    ("centre_err = lo - c", "centre"), ("x = NormaliseHU(ct)", "normalise"),
    ("voxels labelled 3", "labelled"), ("a tumour of 2 ml", "tumour"),
    ("in millimetres", "millimetres"), ("its behaviour under load", "behaviour"),
    ("we analysed it", "analysed"), ("whilst holding the lock", "whilst"),
    ("CC BY licence", "licence"), ("the oesophagus", "oesophagus"),
    ("neighbourhood of radius r", "neighbourhood"), ("summarising", "summarising"),
    ("pass  # ZipStore uninitialised", "uninitialised"), ("def test_unmodelled_keys():", "unmodelled"),
    ("const greyLevel = 0;", "grey"), ("the errors cancelled", "cancelled"),
])
def test_catches_prose_and_identifiers(line, word):
    assert word in [t for t, _ in british_in(line)]


@pytest.mark.parametrize("line", [
    "the center of the box", "colorMap", "canceled",
    "advise exercise precise noise otherwise premise expertise compromise surprise",
    "four contour your hour", "parameter diameter perimeter", "two analyses of emphasis",
    "organism organization", "gray labeled modeling tumor neighbor behavior license analyze normalize",
    # spec and wire names duckn carries: none may ever trip the guard
    '"centering": "cell", "measurement_frame": [[1, 0, 0]]', "WindowCenter (0028,1050)",
    "Segment0_LabelValue Segment0_Color Segmentation_MasterRepresentation", "space origin: (0,0,0)",
])
def test_spares_american_shared_and_spec_words(line):
    assert british_in(line) == []


def test_a_pragma_allows_only_its_word_on_its_line(tmp_path):
    (tmp_path / "x.py").write_text("c = sw.centre  # spelling: allow centre\n"
                                   "colour = 1  # spelling: allow centre\n"
                                   "ok = 2  # spelling: allow grey\n")
    (tmp_path / "x.md").write_text('DICOM calls it "Colour" <!-- spelling: allow colour -->\n')
    bad, stale = scan(["x.py", "x.md"], root=tmp_path)
    assert bad == ["x.py:2: 'colour' -> 'color'"]
    assert len(stale) == 2                                     # line 2's centre and line 3's grey are not there
