"""Tests for .seg.nrrd key/value parsing into SegmentationExtension."""

from __future__ import annotations

from pathlib import Path

import nrrd
import pytest

from duckn.models import SegmentationExtension
from duckn.seg_nrrd import parse_seg_keyvalues, serialize_seg_extension

DATA_DIR = Path(__file__).parent / "data" / "real-world"

SEG_NRRD_FILES = sorted(DATA_DIR.glob("*.seg.nrrd"))


# ---------------------------------------------------------------------------
# Unit tests for parse_seg_keyvalues
# ---------------------------------------------------------------------------


def test_no_segmentation_keys():
    """Non-segmentation keyvalues should return None and pass through."""
    kv = {"foo": "bar", "baz": "42"}
    ext, remaining = parse_seg_keyvalues(kv)
    assert ext is None
    assert remaining == kv


def test_minimal_segment():
    """A single segment with only ID and LabelValue should parse."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, remaining = parse_seg_keyvalues(kv)
    assert ext is not None
    assert remaining == {}
    assert len(ext.segments) == 1
    assert ext.segments[0].id == "S1"
    assert ext.segments[0].label_value == 1
    assert ext.version == "1.0"


def test_global_fields():
    """Global Segmentation_* fields should parse correctly."""
    kv = {
        "Segmentation_MasterRepresentation": "Binary labelmap",
        "Segmentation_ContainedRepresentationNames": "Binary labelmap|Closed surface|",
        "Segmentation_ReferenceImageExtentOffset": "0 0 0",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, remaining = parse_seg_keyvalues(kv)
    assert ext is not None
    assert ext.source_representation == "binary-labelmap"
    assert ext.contained_representations == ["binary-labelmap", "closed-surface"]
    assert ext.reference_extent_offset == [0, 0, 0]


def test_source_representation_preferred_over_master():
    """SourceRepresentation should take precedence over MasterRepresentation."""
    kv = {
        "Segmentation_MasterRepresentation": "Binary labelmap",
        "Segmentation_SourceRepresentation": "Fractional labelmap",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext is not None
    assert ext.source_representation == "fractional-labelmap"


def test_conversion_parameters():
    """ConversionParameters should parse name|value|description."""
    kv = {
        "Segmentation_ConversionParameters": (
            "Smoothing factor|0.5|Range: 0.0 to 1.0.&"
            "Joint smoothing|0|Perform joint smoothing.&"
        ),
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext is not None
    assert "Smoothing factor" in ext.conversion_parameters
    assert ext.conversion_parameters["Smoothing factor"].value == "0.5"
    assert ext.conversion_parameters["Smoothing factor"].description == "Range: 0.0 to 1.0."
    assert ext.conversion_parameters["Joint smoothing"].value == "0"


def test_conversion_parameters_escaped_newlines():
    """Backslash-n in descriptions should be unescaped."""
    kv = {
        "Segmentation_ConversionParameters": r"End capping|1|Line1.\nLine2.&",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext.conversion_parameters["End capping"].description == "Line1.\nLine2."


def test_segment_fields():
    """Per-segment scalar fields should parse correctly."""
    kv = {
        "Segment0_ID": "Seg1",
        "Segment0_Name": "Liver",
        "Segment0_NameAutoGenerated": "0",
        "Segment0_Color": "0.5 0.6 0.7",
        "Segment0_ColorAutoGenerated": "1",
        "Segment0_LabelValue": "3",
        "Segment0_Layer": "2",
        "Segment0_Extent": "10 20 30 40 50 60",
    }
    ext, _ = parse_seg_keyvalues(kv)
    seg = ext.segments[0]
    assert seg.id == "Seg1"
    assert seg.name == "Liver"
    assert seg.name_auto_generated is False
    assert seg.color == [0.5, 0.6, 0.7]
    assert seg.color_auto_generated is True
    assert seg.label_value == 3
    assert seg.layer == 2
    assert seg.extent == [10, 20, 30, 40, 50, 60]


def test_multi_label_value():
    """Space-separated label values should become a list."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "2 3",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext.segments[0].label_value == [2, 3]


def test_tags_and_terminology():
    """Tags including TerminologyEntry should parse into dicom/designations/tags."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": (
            "Segmentation.Status:inprogress|"
            "TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list"
            "~SCT^85756007^Tissue~SCT^85756007^Tissue~^^"
            "~Anatomic codes - DICOM master list~^^~^^|"
        ),
    }
    ext, _ = parse_seg_keyvalues(kv)
    seg = ext.segments[0]

    # Tags (non-terminology)
    assert seg.tags == {"Status": "inprogress"}

    # DICOM classification
    assert seg.dicom is not None
    assert seg.dicom.category.scheme == "SCT"
    assert seg.dicom.category.code == "85756007"
    assert seg.dicom.category.meaning == "Tissue"
    assert seg.dicom.type.code == "85756007"

    # Designation from type code
    assert seg.designations is not None
    assert len(seg.designations) == 1
    assert seg.designations[0].scheme == "SCT"
    assert seg.designations[0].code == "85756007"

    # Terminology registry
    assert ext.terminologies is not None
    assert "SCT" in ext.terminologies
    assert ext.terminologies["SCT"].name == "SNOMED Clinical Terms"


def test_empty_dicom_omitted():
    """If all DICOM code slots are empty, dicom should be None."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": "TerminologyEntry:ctx1~^^~^^~^^~ctx2~^^~^^|",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext.segments[0].dicom is None
    assert ext.segments[0].designations is None


def test_remaining_keys_preserved():
    """Non-segmentation keys should be returned in remaining dict."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "CustomKey": "custom_value",
        "Segmentation_MasterRepresentation": "Binary labelmap",
    }
    ext, remaining = parse_seg_keyvalues(kv)
    assert ext is not None
    assert remaining == {"CustomKey": "custom_value"}


def test_multiple_segments_ordered():
    """Segments should be ordered by index."""
    kv = {
        "Segment2_ID": "C",
        "Segment2_LabelValue": "3",
        "Segment0_ID": "A",
        "Segment0_LabelValue": "1",
        "Segment1_ID": "B",
        "Segment1_LabelValue": "2",
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert [s.id for s in ext.segments] == ["A", "B", "C"]


def test_srt_terminology_known():
    """SRT scheme should map to 'DICOM SR Coding Scheme'."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": (
            "TerminologyEntry:ctx~SRT^T-D0050^Tissue~SRT^T-D0050^Tissue~^^~ctx~^^~^^|"
        ),
    }
    ext, _ = parse_seg_keyvalues(kv)
    assert ext.terminologies["SRT"].name == "DICOM SR Coding Scheme"


def test_model_validates():
    """Parsed extension should validate against SegmentationExtension model."""
    kv = {
        "Segmentation_MasterRepresentation": "Binary labelmap",
        "Segmentation_ContainedRepresentationNames": "Binary labelmap|",
        "Segmentation_ReferenceImageExtentOffset": "0 0 0",
        "Segment0_ID": "Seg1",
        "Segment0_Name": "Full",
        "Segment0_LabelValue": "1",
        "Segment0_Layer": "0",
        "Segment0_Color": "0.5 0.6 0.7",
        "Segment0_ColorAutoGenerated": "1",
        "Segment0_NameAutoGenerated": "0",
        "Segment0_Extent": "10 20 30 40 50 60",
        "Segment0_Tags": (
            "Segmentation.Status:inprogress|"
            "TerminologyEntry:ctx~SCT^85756007^Tissue~SCT^85756007^Tissue~^^~ctx~^^~^^|"
        ),
    }
    ext, _ = parse_seg_keyvalues(kv)
    # Round-trip through model_dump → SegmentationExtension
    dumped = ext.model_dump(exclude_none=True)
    reloaded = SegmentationExtension(**dumped)
    assert reloaded.segments[0].id == "Seg1"


# ---------------------------------------------------------------------------
# Integration tests against real-world .seg.nrrd files
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "seg_file",
    SEG_NRRD_FILES,
    ids=[f.name for f in SEG_NRRD_FILES],
)
def test_real_world_parses(seg_file: Path):
    """Each real-world .seg.nrrd file should parse without errors."""
    header = nrrd.read_header(str(seg_file))
    keyvalues: dict[str, str] = {}
    for k, v in header.items():
        if not k.startswith(("type", "dimension", "space", "sizes", "encoding", "endian",
                             "kinds", "data file", "datafile", "content",
                             "sample units", "spacings", "thicknesses",
                             "axis m", "axism", "centerings", "labels", "units",
                             "min", "max", "old", "number", "line", "byte")):
            keyvalues[k] = str(v)

    ext, remaining = parse_seg_keyvalues(keyvalues)
    assert ext is not None, f"No segmentation found in {seg_file.name}"
    assert len(ext.segments) > 0

    # Validate model round-trip
    dumped = ext.model_dump(exclude_none=True)
    reloaded = SegmentationExtension(**dumped)
    assert len(reloaded.segments) == len(ext.segments)


@pytest.mark.parametrize(
    "seg_file",
    SEG_NRRD_FILES,
    ids=[f.name for f in SEG_NRRD_FILES],
)
def test_real_world_no_seg_keys_in_remaining(seg_file: Path):
    """After parsing, no Segment* or Segmentation_* keys should remain."""
    header = nrrd.read_header(str(seg_file))
    keyvalues: dict[str, str] = {}
    for k, v in header.items():
        if not k.startswith(("type", "dimension", "space", "sizes", "encoding", "endian",
                             "kinds", "data file", "datafile", "content",
                             "sample units", "spacings", "thicknesses",
                             "axis m", "axism", "centerings", "labels", "units",
                             "min", "max", "old", "number", "line", "byte")):
            keyvalues[k] = str(v)

    _, remaining = parse_seg_keyvalues(keyvalues)
    for key in remaining:
        assert not key.startswith("Segment"), f"Seg key leaked to remaining: {key}"
        assert not key.startswith("Segmentation_"), f"Seg key leaked to remaining: {key}"


@pytest.mark.parametrize(
    "seg_file",
    SEG_NRRD_FILES,
    ids=[f.name for f in SEG_NRRD_FILES],
)
def test_real_world_segment_ids_unique(seg_file: Path):
    """Segment IDs within each file should be unique."""
    header = nrrd.read_header(str(seg_file))
    keyvalues: dict[str, str] = {}
    for k, v in header.items():
        if not k.startswith(("type", "dimension", "space", "sizes", "encoding", "endian",
                             "kinds", "data file", "datafile", "content",
                             "sample units", "spacings", "thicknesses",
                             "axis m", "axism", "centerings", "labels", "units",
                             "min", "max", "old", "number", "line", "byte")):
            keyvalues[k] = str(v)

    ext, _ = parse_seg_keyvalues(keyvalues)
    ids = [s.id for s in ext.segments]
    assert len(ids) == len(set(ids)), f"Duplicate segment IDs in {seg_file.name}: {ids}"


# ---------------------------------------------------------------------------
# Round-trip tests: parse → serialize → re-parse
# ---------------------------------------------------------------------------


def test_serialize_minimal():
    """Minimal extension should serialize and re-parse."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Name": "Liver",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    ext2, _ = parse_seg_keyvalues(flat)
    assert ext2.segments[0].id == "S1"
    assert ext2.segments[0].name == "Liver"
    assert ext2.segments[0].label_value == 1


def test_serialize_global_fields():
    """Global fields should round-trip through serialize."""
    kv = {
        "Segmentation_MasterRepresentation": "Binary labelmap",
        "Segmentation_ContainedRepresentationNames": "Binary labelmap|Closed surface|",
        "Segmentation_ReferenceImageExtentOffset": "0 0 0",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)

    assert flat["Segmentation_MasterRepresentation"] == "Binary labelmap"
    assert "Binary labelmap" in flat["Segmentation_ContainedRepresentationNames"]
    assert "Closed surface" in flat["Segmentation_ContainedRepresentationNames"]
    assert flat["Segmentation_ReferenceImageExtentOffset"] == "0 0 0"


def test_serialize_conversion_parameters():
    """ConversionParameters should round-trip, re-escaping newlines."""
    kv = {
        "Segmentation_ConversionParameters": r"End capping|1|Line1.\nLine2.&Factor|0.5|Desc.&",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    ext2, _ = parse_seg_keyvalues(flat)
    assert ext2.conversion_parameters["End capping"].description == "Line1.\nLine2."
    assert ext2.conversion_parameters["Factor"].value == "0.5"


def test_serialize_segment_fields():
    """All per-segment fields should round-trip."""
    kv = {
        "Segment0_ID": "Seg1",
        "Segment0_Name": "Liver",
        "Segment0_NameAutoGenerated": "0",
        "Segment0_Color": "0.5 0.6 0.7",
        "Segment0_ColorAutoGenerated": "1",
        "Segment0_LabelValue": "3",
        "Segment0_Layer": "2",
        "Segment0_Extent": "10 20 30 40 50 60",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    ext2, _ = parse_seg_keyvalues(flat)
    seg = ext2.segments[0]
    assert seg.name == "Liver"
    assert seg.name_auto_generated is False
    assert seg.color == [0.5, 0.6, 0.7]
    assert seg.color_auto_generated is True
    assert seg.label_value == 3
    assert seg.layer == 2
    assert seg.extent == [10, 20, 30, 40, 50, 60]


def test_serialize_tags_and_dicom():
    """Tags + TerminologyEntry should round-trip through serialize."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": (
            "Segmentation.Status:inprogress|"
            "TerminologyEntry:ctx~SCT^85756007^Tissue~SCT^85756007^Tissue~^^~ctx~^^~^^|"
        ),
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    ext2, _ = parse_seg_keyvalues(flat)
    seg = ext2.segments[0]
    assert seg.tags == {"Status": "inprogress"}
    assert seg.dicom.category.code == "85756007"
    assert seg.designations[0].scheme == "SCT"


def test_serialize_multi_label():
    """Multi-value label_value should round-trip."""
    kv = {
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "2 3",
    }
    ext, _ = parse_seg_keyvalues(kv)
    flat = serialize_seg_extension(ext)
    ext2, _ = parse_seg_keyvalues(flat)
    assert ext2.segments[0].label_value == [2, 3]


@pytest.mark.parametrize(
    "seg_file",
    SEG_NRRD_FILES,
    ids=[f.name for f in SEG_NRRD_FILES],
)
def test_real_world_round_trip(seg_file: Path):
    """parse → serialize → re-parse should preserve segment structure."""
    header = nrrd.read_header(str(seg_file))
    keyvalues: dict[str, str] = {}
    for k, v in header.items():
        if not k.startswith(("type", "dimension", "space", "sizes", "encoding", "endian",
                             "kinds", "data file", "datafile", "content",
                             "sample units", "spacings", "thicknesses",
                             "axis m", "axism", "centerings", "labels", "units",
                             "min", "max", "old", "number", "line", "byte")):
            keyvalues[k] = str(v)

    ext1, _ = parse_seg_keyvalues(keyvalues)
    flat = serialize_seg_extension(ext1)
    ext2, remaining = parse_seg_keyvalues(flat)

    assert len(ext2.segments) == len(ext1.segments)
    assert [s.id for s in ext2.segments] == [s.id for s in ext1.segments]
    assert [s.name for s in ext2.segments] == [s.name for s in ext1.segments]
    assert [s.label_value for s in ext2.segments] == [s.label_value for s in ext1.segments]
    assert ext2.source_representation == ext1.source_representation
    assert not remaining  # no leaked keys


# ---------------------------------------------------------------------------
# Legacy fidelity tests: unmodified model replays original strings
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "seg_file",
    SEG_NRRD_FILES,
    ids=[f.name for f in SEG_NRRD_FILES],
)
def test_real_world_byte_exact_with_legacy(seg_file: Path):
    """Unmodified model should replay original strings byte-exactly."""
    header = nrrd.read_header(str(seg_file))
    keyvalues: dict[str, str] = {}
    for k, v in header.items():
        if not k.startswith(("type", "dimension", "space", "sizes", "encoding", "endian",
                             "kinds", "data file", "datafile", "content",
                             "sample units", "spacings", "thicknesses",
                             "axis m", "axism", "centerings", "labels", "units",
                             "min", "max", "old", "number", "line", "byte")):
            keyvalues[k] = str(v)

    ext, _ = parse_seg_keyvalues(keyvalues)
    flat = serialize_seg_extension(ext)

    # Every consumed seg key should come back byte-exact
    for key in keyvalues:
        if key.startswith("Segment") or key.startswith("Segmentation_"):
            assert flat.get(key) == keyvalues[key], (
                f"{key} mismatch:\n  orig: {keyvalues[key]!r}\n  got:  {flat.get(key)!r}"
            )


def test_legacy_dropped_when_model_modified():
    """If the model is modified, legacy should be ignored and fresh strings generated."""
    kv = {
        "Segmentation_SourceRepresentation": "Binary labelmap",
        "Segment0_ID": "S1",
        "Segment0_LabelValue": "1",
        "Segment0_Tags": (
            "TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list"
            "~SCT^85756007^Tissue~SCT^85756007^Tissue~^^"
            "~Anatomic codes - DICOM master list~^^~^^|"
        ),
    }
    ext, _ = parse_seg_keyvalues(kv)

    # Modify the model
    ext.segments[0].name = "Modified"

    flat = serialize_seg_extension(ext)
    # Should use generated values, not legacy
    assert flat["Segment0_Name"] == "Modified"
    # Key falls back to MasterRepresentation (generated default)
    assert "Segmentation_MasterRepresentation" in flat

